var _ = require('lodash');
const tree = [
  {
    children: [
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1030000',
            enabled: true,
            id: null,
            module: 'landingpage-list-add-copy-edit',
            name: '新建/复制/编辑',
            new: true,
            parentId: 10300,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1030003',
            enabled: true,
            id: null,
            module: 'landingpage-list-del-recovery',
            name: '删除/恢复落地页',
            new: true,
            parentId: 10300,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1030100',
            enabled: true,
            id: null,
            module: 'landingpage-linkmen-export',
            name: '导出',
            new: true,
            parentId: 10300,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10300',
        enabled: true,
        id: null,
        module: null,
        name: '列表管理',
        new: true,
        parentId: 103,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1030200',
            enabled: true,
            id: null,
            module: 'landingpage-folder-add-edit',
            name: '新建/编辑',
            new: true,
            parentId: 10302,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1030202',
            enabled: true,
            id: null,
            module: 'landingpage-folder-del',
            name: '删除',
            new: true,
            parentId: 10302,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1030203',
            enabled: true,
            id: null,
            module: 'landingpage-folder-move',
            name: '移入分组',
            new: true,
            parentId: 10302,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1030204',
            enabled: true,
            id: null,
            module: 'landingpage-folder-remove',
            name: '移出分组',
            new: true,
            parentId: 10302,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10302',
        enabled: true,
        id: null,
        module: null,
        name: '分组管理',
        new: true,
        parentId: 103,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1030302',
            enabled: true,
            id: null,
            module: 'landingpage-list-del-complete',
            name: '清空/删除',
            new: true,
            parentId: 10303,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10303',
        enabled: true,
        id: null,
        module: null,
        name: '回收站',
        new: true,
        parentId: 103,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1050000',
            enabled: true,
            id: null,
            module: 'tools-form-add-edit',
            name: '新建/编辑',
            new: true,
            parentId: 10500,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1050002',
            enabled: true,
            id: null,
            module: 'tools-form-del',
            name: '删除',
            new: true,
            parentId: 10500,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10500',
        enabled: true,
        id: null,
        module: null,
        name: '表单模板',
        new: true,
        parentId: 103,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1050200',
            enabled: true,
            id: null,
            module: 'tools-comment-add-edit',
            name: '新建/编辑',
            new: true,
            parentId: 10502,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1050202',
            enabled: true,
            id: null,
            module: 'tools-comment-del',
            name: '删除',
            new: true,
            parentId: 10502,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10502',
        enabled: true,
        id: null,
        module: null,
        name: '评论模板',
        new: true,
        parentId: 103,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1050300',
            enabled: true,
            id: null,
            module: 'tools-order-add-edit',
            name: '新建/编辑',
            new: true,
            parentId: 10503,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1050302',
            enabled: true,
            id: null,
            module: 'tools-order-del',
            name: '删除',
            new: true,
            parentId: 10503,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10503',
        enabled: true,
        id: null,
        module: null,
        name: '订单模板',
        new: true,
        parentId: 103,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
    ],
    createdAt: null,
    eid: '103',
    enabled: true,
    id: null,
    module: null,
    name: '落地页',
    new: true,
    parentId: null,
    permission: false,
    relId: null,
    status: null,
    type: '0',
    updatedAt: null,
    version: null,
  },
  {
    children: [
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1020100',
            enabled: true,
            id: null,
            module: 'system-linkmen-add-edit',
            name: '新建/编辑',
            new: true,
            parentId: 10201,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1020102',
            enabled: true,
            id: null,
            module: 'system-linkmen-del',
            name: '删除',
            new: true,
            parentId: 10201,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10201',
        enabled: true,
        id: null,
        module: null,
        name: '客资状态管理',
        new: true,
        parentId: 104,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1040000',
            enabled: true,
            id: null,
            module: 'linkmen-list-edit',
            name: '编辑',
            new: true,
            parentId: 10400,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1040003',
            enabled: true,
            id: null,
            module: 'linkmen-list-del',
            name: '删除',
            new: true,
            parentId: 10400,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1040004',
            enabled: true,
            id: null,
            module: 'linkmen-list-export',
            name: '导出',
            new: true,
            parentId: 10400,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1040005',
            enabled: true,
            id: null,
            module: 'linkman-new-entry',
            name: '新增',
            new: true,
            parentId: 10400,
            permission: false,
            relId: null,
            status: null,
            type: '3',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10400',
        enabled: true,
        id: null,
        module: null,
        name: '列表管理',
        new: true,
        parentId: 104,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1040100',
            enabled: true,
            id: null,
            module: 'linkmen-folders-add-eidt',
            name: '新建/编辑',
            new: true,
            parentId: 10401,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1040102',
            enabled: true,
            id: null,
            module: 'linkmen-folders-del',
            name: '删除',
            new: true,
            parentId: 10401,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10401',
        enabled: true,
        id: null,
        module: null,
        name: '智能文件夹',
        new: true,
        parentId: 104,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
    ],
    createdAt: null,
    eid: '104',
    enabled: true,
    id: null,
    module: null,
    name: '客资',
    new: true,
    parentId: null,
    permission: false,
    relId: null,
    status: null,
    type: '0',
    updatedAt: null,
    version: null,
  },
  {
    children: [
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1070000',
            enabled: true,
            id: null,
            module: 'data-behavior-export',
            name: '导出',
            new: true,
            parentId: 10700,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10700',
        enabled: true,
        id: null,
        module: null,
        name: '用户行为分析',
        new: true,
        parentId: 107,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
    ],
    createdAt: null,
    eid: '107',
    enabled: true,
    id: null,
    module: null,
    name: '数据',
    new: true,
    parentId: null,
    permission: false,
    relId: null,
    status: null,
    type: '0',
    updatedAt: null,
    version: null,
  },
  {
    children: [
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1020000',
            enabled: true,
            id: null,
            module: 'system-sms-add-edit',
            name: '新建/编辑',
            new: true,
            parentId: 10200,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1020002',
            enabled: true,
            id: null,
            module: 'system-sms-del',
            name: '删除',
            new: true,
            parentId: 10200,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10200',
        enabled: true,
        id: null,
        module: null,
        name: '短信签名管理',
        new: true,
        parentId: 109,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1050100',
            enabled: true,
            id: null,
            module: 'tools-sms-add-edit',
            name: '新建/编辑',
            new: true,
            parentId: 10501,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1050102',
            enabled: true,
            id: null,
            module: 'tools-sms-del',
            name: '删除',
            new: true,
            parentId: 10501,
            permission: false,
            relId: null,
            status: null,
            type: '1',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '10501',
        enabled: true,
        id: null,
        module: null,
        name: '短信模板',
        new: true,
        parentId: 109,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
    ],
    createdAt: null,
    eid: '109',
    enabled: true,
    id: null,
    module: null,
    name: '工具',
    new: true,
    parentId: null,
    permission: false,
    relId: null,
    status: null,
    type: '0',
    updatedAt: null,
    version: null,
  },
  {
    children: [
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1101000',
            enabled: true,
            id: null,
            module: 'ad-list-strategy',
            name: '选择/开启/关闭策略',
            new: true,
            parentId: 11000,
            permission: false,
            relId: null,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1101001',
            enabled: true,
            id: null,
            module: 'ad-list-two-confirmation',
            name: '开启/关闭二次确认',
            new: true,
            parentId: 11000,
            permission: false,
            relId: null,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1101002',
            enabled: true,
            id: null,
            module: 'ad-list-configured-status',
            name: '开启/关闭广告',
            new: true,
            parentId: 11000,
            permission: false,
            relId: null,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1101003',
            enabled: true,
            id: null,
            module: 'ad-list-strategy-exec-record',
            name: '执行记录',
            new: true,
            parentId: 11000,
            permission: true,
            relId: 2552,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1101004',
            enabled: true,
            id: null,
            module: 'ad-list-sub-member',
            name: '人员管理',
            new: true,
            parentId: 11000,
            permission: false,
            relId: null,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1101005',
            enabled: true,
            id: null,
            module: 'ad-list-account-setting',
            name: '账户设置',
            new: true,
            parentId: 11000,
            permission: false,
            relId: null,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '11000',
        enabled: true,
        id: null,
        module: null,
        name: '广告列表',
        new: true,
        parentId: 110,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
      {
        children: [
          {
            children: null,
            createdAt: null,
            eid: '1100000',
            enabled: true,
            id: null,
            module: 'strategy-list-edit',
            name: '新建/编辑策略',
            new: true,
            parentId: 11001,
            permission: false,
            relId: null,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1100001',
            enabled: true,
            id: null,
            module: 'strategy-list-delete',
            name: '删除策略',
            new: true,
            parentId: 11001,
            permission: false,
            relId: null,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
          {
            children: null,
            createdAt: null,
            eid: '1100002',
            enabled: true,
            id: null,
            module: 'strategy-list-strategy-exec-record',
            name: '执行记录',
            new: true,
            parentId: 11001,
            permission: false,
            relId: null,
            status: null,
            type: '2',
            updatedAt: null,
            version: null,
          },
        ],
        createdAt: null,
        eid: '11001',
        enabled: true,
        id: null,
        module: null,
        name: '策略库',
        new: true,
        parentId: 110,
        permission: false,
        relId: null,
        status: null,
        type: '1',
        updatedAt: null,
        version: null,
      },
    ],
    createdAt: null,
    eid: '110',
    enabled: true,
    id: null,
    module: null,
    name: '自动化',
    new: true,
    parentId: null,
    permission: false,
    relId: null,
    status: null,
    type: '0',
    updatedAt: null,
    version: null,
  },
]
const eid = '11000'
const value = [ '1101000', '1101001', '1101002', '1101003', '1101004', '1101005', '44443', '678' ]
// console.log(_.find(tree, i => console.log(i.childern)));
const aModu = _.find(tree, i => _.find(i.children, ic => ic.eid === eid)).children
const bModu = _.find(aModu, i => i.eid === eid).children
const cModu = bModu.map(i => _.get(i, ['eid']))
console.log(cModu);


